export default {
    // API_BASE_URL: "http://10.42.0.84:8000",
    // API_BASE_URL: "http://192.168.43.139:8000/",
    // API_BASE_URL: "http://192.168.137.160:8000",
    API_BASE_URL: "http://66.70.190.240:8000",

    LOGIN: '/api/user/login',
    REGISTER: '/api/user/register',
    LOGOUT: '/api/user/logout',
    TAMBAH_TAMBAK : '/api/tambak',
    GET_TAMBAK : '/api/tambak',
    LIST_TAMBAK : '/api/tambak/last-monitor/',
    DETAIL_TAMBAK : '/api/tambak/',
    NOTIF : '/api/notif/',
    DETAIL_NOTIF : '/api/notif/detail/',
    INFO : '/api/info',
    PANDUAN : '/api/panduan',
    MONITOR : '/api/tambak/monitor/',
    EDIT_TAMBAK : '/api/tambak/',
    USER : '/api/user',
    CHANGE_PASS: '/api/user/password',
    PUSHNOTIF: '/api/push-notif',
    SAVENOTIF: '/api/save-notif',
    CREATE_INFO: '/api/info', 
    EDIT_INFO: '/api/info/', 
    DELETE_INFO: '/api/info/',
    CREATE_PANDUAN: '/api/panduan', 
    EDIT_PANDUAN: '/api/panduan/', 
    DELETE_PANDUAN: '/api/panduan/',
    EDIT_JADWAL: '/api/jadwal/'
}